### ISSUE TITLE
 Extending SSIS with .NET Scripting 

### ISSUE THREAD

**Issue by kiquenet** [fizalihsan/PlayArea#1]
http://it-ebooks.info/book/6429 - Extending SSIS with .NET Scripting - Free Download eBook - pdf - 2015

Free Download ?

**Comment by fizalihsan** [comment]
I'm afraid not

**Comment by kiquenet** [comment]
I get.it in japanese page

**Comment by fizalihsan** [comment]
I don't own that site. So I can't comment
